Telemetry/Controllers/TelemetrySessionsController.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MongoDB.Bson;
using MongoDB.Driver;
using Telemetry.Configuration;
using Telemetry.Entities.Models;
using Telemetry.Services.Commands;
using Telemetry.Services.Mappers;
using Telemetry.ViewModels;
using JsonSerializer = System.Text.Json.JsonSerializer;

namespace Telemetry.Controllers;

public class TelemetrySessionsController : Controller
{
    private readonly UserManager<User> _userManager;
    private readonly ILogger<TelemetrySessionsController> _logger;
    private readonly IMongoCollection<User> _users;
    private readonly ITelemetrySessionMapper _mapper;
    private readonly ISender _mediator;

    public TelemetrySessionsController(IMongoClient mongoClient, ILogger<TelemetrySessionsController> logger,
        UserManager<User> userManager, ITelemetrySessionMapper mapper, ISender mediator, IOptions<MongoDbSettings> mongoDbSettings)
    {
        _logger = logger;
        _userManager = userManager;
        var mongoDb = mongoClient.GetDatabase(mongoDbSettings.Value.DatabaseName);
        _users = mongoDb.GetCollection<User>(mongoDbSettings.Value.UsersCollectionName);
        _mapper = mapper;
        _mediator = mediator;
    }

    ////// GET: TelemetrySessions
    [Authorize]
    public async Task<IActionResult> Index()
    {
        var user = await _userManager.GetUserAsync(User);

        return View(await _mapper.Map(user.Sessions));
    }

    ////// GET: TelemetrySessions/Details/5
    [Authorize]
    public async Task<IActionResult> Details(string? id)
    {
        var user = await _userManager.GetUserAsync(User);
        if (id is null)
            return NotFound();

        var telemetrySession = user.Sessions.FirstOrDefault(s => s.Id == ObjectId.Parse(id));

        if (telemetrySession is null)
        {
            return NotFound();
        }

        return View(_mapper.Map(telemetrySession, user));
    }

    ////// GET: TelemetrySessions/Delete/5
    [Authorize]
    public async Task<IActionResult> Delete(string? id)
    {
        if (id is null)
            return NotFound();

        var user = await _userManager.GetUserAsync(User);

        var telemetrySession = user.Sessions.FirstOrDefault(s => s.Id == ObjectId.Parse(id));

        if (telemetrySession is null)
        {
            return NotFound();
        }

        return View(_mapper.Map(telemetrySession, user));
    }

    ////// POST: TelemetrySessions/Delete/5
    [HttpPost, ActionName("Delete")]
    [Authorize]
    public async Task<IActionResult> DeleteConfirmed(string id)
    {
        var user = await _userManager.GetUserAsync(User);

        var updateDefinition =
            Builders<User>.Update.PullFilter(u => u.Sessions, s => s.Id == ObjectId.Parse(id));

        await _users.FindOneAndUpdateAsync(u => u.Id == user.Id, updateDefinition);

        return RedirectToAction(nameof(Index));
    }

    [Authorize]
    public async Task<IActionResult> CreateNewSession()
    {
        var currentUser = await _userManager.GetUserAsync(User);

        var session = new TelemetrySession
        {
            Id = ObjectId.GenerateNewId(),
            UserId = currentUser.Id,
            Status = 1,
            SessionDate = DateTime.UtcNow,
            Pages = new List<Page>()
        };

        var updateDefinition = Builders<User>.Update.Push(u => u.Sessions, session);

        _logger.LogInformation("Before creating new session");
        await _users.UpdateOneAsync(u => u.Id == currentUser.Id, updateDefinition);
        _logger.LogInformation("After creating new session");


        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> ChangeSessionStatus(string id)
    {
        var searchDefinition = Builders<User>.Filter.Eq(u => u.Id, id);
        var sessionUser = await _users.Find(searchDefinition).FirstOrDefaultAsync();
        sessionUser.Sessions.ForEach(s => s.Status = 0);
            

        await _users.UpdateOneAsync(u => u.Id == id, Builders<User>.Update.Set(s => s.Sessions, sessionUser.Sessions));
            
        _logger.LogInformation("Session status changed to 0");

        return RedirectToAction("Index", "Home");
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> SendInformationToSession([FromBody] SessionInfoRequest request)
    {
        await _mediator.Send(new SendInformationToSessionCommand(request));
        
        return Ok();
    }
}

Telemetry/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Telemetry.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Telemetry</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Gallery">Gallery</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TelemetrySessions" asp-action="Index">Sessions</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Telemetry - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @if (User.Identity.IsAuthenticated)
    {
        <script src="~/js/site.js"></script>
    }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>